name: C/C++ CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install arm-none-eabi-*
      run: sudo apt-get update && sudo apt-get install gcc-arm-none-eabi
    - name: make debug
      run: cd Debug/ && make -j8 all
      
    - name: collect artifacts
      run: mkdir build && cp Debug/*.elf build
      
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: debug build
        path: build
